---

- hosts: ocata_controller
  vars_files:
  - /root/ha_ocata/group_vars/all 
  tasks:
  - name:
    shell: source /home/admin-openrc.sh;
           su -s /bin/sh -c "nova-manage cell_v2 discover_hosts --verbose" nova
