---

- hosts: ocata
  tasks:
  - name: 禁用selinux
    shell: sed -i "s/^SELINUX=.*/SELINUX=disabled/" /etc/selinux/config

- hosts: controller_standby
  tasks:
  - name: 防火墙规则设置
    shell: firewall-cmd --zone=public --permanent --add-port=123/udp;
           firewall-cmd --zone=public --permanent --add-port=80/tcp;
           firewall-cmd --zone=public --permanent --add-port=2224/tcp;
           firewall-cmd --zone=public --permanent --add-port=5404-5405/udp;
           firewall-cmd --zone=public --permanent --add-port=8888/tcp;
           firewall-cmd --zone=public --permanent --add-port=3306/tcp --add-port=4444/tcp --add-port=4567/tcp --add-port=4567/udp --add-port=4568/tcp;
           firewall-cmd --zone=public --permanent --add-port=4369/tcp --add-port=5672/tcp --add-port=25672/tcp;
           firewall-cmd --zone=public --permanent --add-port=11211/tcp;
           firewall-cmd --zone=public --permanent --add-port=5000/tcp --add-port=35357/tcp;
           firewall-cmd --zone=public --permanent --add-port=9292/tcp --add-port=9191/tcp;
           firewall-cmd --zone=public --permanent --add-port=8773-8778/tcp;
           firewall-cmd --zone=public --permanent --add-port=6082/tcp;
           firewall-cmd --zone=public --permanent --add-port=9696/tcp --add-port=8472/udp;
  - name: 重启防火墙
    shell: firewall-cmd --reload

- hosts: ocata_compute
  tasks:
  - name: 打开特定端口
    shell: firewall-cmd --zone=public --permanent --add-port=5900-5999/tcp --add-port=8472/udp;
  - name: 重启防火墙
    shell: firewall-cmd --reload
