---

- name: 导入keystone数据库
  shell: mysql -uroot -p{{DB_PASS}}< {{MAJOR_CONF_PATH}}/keystone/keystone.sql
- name: 配置keystone.conf
  shell: crudini --set /etc/keystone/keystone.conf DEFAULT admin_token 7027356a188bc8247884;
         crudini --set /etc/keystone/keystone.conf database connection "mysql+pymysql://keystone:KEYSTONE_DBPASS@{{MAJOR_IP}}/keystone";
         crudini --set /etc/keystone/keystone.conf database slave_connection "mysql+pymysql://keystone:KEYSTONE_DBPASS@{{STANDBY_IP}}/keystone";
         crudini --set /etc/keystone/keystone.conf token provider fernet;
         crudini --set /etc/keystone/keystone.conf catalog driver keystone.catalog.backends.sql.Catalog;
         crudini --set /etc/keystone/keystone.conf identity driver keystone.identity.backends.sql.Identity;
         crudini --set /etc/keystone/keystone.conf DEFAULT bind_host {{MAJOR_IP}}
- name: 初始化身份认证服务的数据库
  shell: su -s /bin/sh -c "keystone-manage db_sync" keystone;
- name: 初始化Fernet keys
  shell: keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone;
- name: 复制fernet-keys到备用节点
  shell: scp -r /etc/keystone/fernet-keys {{STANDBY_IP}}:/etc/keystone/;
- name: 配置httpd.conf，wsgi-keystone.con
  shell: sed -i "s/^Listen.*/Listen {{MAJOR_IP}}:80/" /etc/httpd/conf/httpd.conf;
         sed -i "s/#ServerName.*/ServerName {{MAJOR_IP}}/" /etc/httpd/conf/httpd.conf;
         sed -i "s/CONTROLLER_IP/{{MAJOR_IP}}/" {{MAJOR_CONF_PATH}}/keystone/wsgi-keystone.conf;
         \cp {{MAJOR_CONF_PATH}}/keystone/wsgi-keystone.conf /etc/httpd/conf.d/
##- name: 配置wsgi-keystone.conf
##  template: src={{mitaka_conf}}/wsgi-keystone.conf.a.js dest=/etc/httpd/conf.d/wsgi-keystone.conf
- name: 启动并设置http服务开机自启
  service: name=httpd state=started enabled=true
- name: 等待2s
  pause: seconds=2
- name: 复制key.sh
  copy: src="{{mitaka_sh}}/key.sh" dest="/root/key.sh"
- name: 创建服务实体和身份认证服务 
  shell: sed -i 's/$CONTROLLER_VIP/{{CONTROLLER_VIP}}/' /root/key.sh;
         sh key.sh
- name: 公共API端点
  shell: bash -login -c 'export OS_TOKEN=7027356a188bc8247884;export OS_URL=http://{{CONTROLLER_VIP}}:35357/v3;export OS_IDENTITY_API_VERSION=3;openstack endpoint create --region RegionOne identity public http://{{CONTROLLER_VIP}}:5000/v3'
- name: 租户API端点
  shell: bash -login -c 'export OS_TOKEN=7027356a188bc8247884;export OS_URL=http://{{CONTROLLER_VIP}}:35357/v3;export OS_IDENTITY_API_VERSION=3;openstack endpoint create --region RegionOne identity internal http://{{CONTROLLER_VIP}}:5000/v3'
- name: 管理API端点
  shell: bash -login -c 'export OS_TOKEN=7027356a188bc8247884;export OS_URL=http://{{CONTROLLER_VIP}}:35357/v3;export OS_IDENTITY_API_VERSION=3;openstack endpoint create --region RegionOne identity admin http://{{CONTROLLER_VIP}}:35357/v3'
- name: 创建域``default``
  shell: bash -login -c 'export OS_TOKEN=7027356a188bc8247884;export OS_URL=http://{{CONTROLLER_VIP}}:35357/v3;export OS_IDENTITY_API_VERSION=3;openstack domain create --description "default Domain" default'
- name: 创建 admin 项目
  shell: bash -login -c 'export OS_TOKEN=7027356a188bc8247884;export OS_URL=http://{{CONTROLLER_VIP}}:35357/v3;export OS_IDENTITY_API_VERSION=3;openstack project create --domain default --description "Admin Project" admin'
- name: 创建 admin 用户
  shell: bash -login -c 'export OS_TOKEN=7027356a188bc8247884;export OS_URL=http://{{CONTROLLER_VIP}}:35357/v3;export OS_IDENTITY_API_VERSION=3;openstack user create --domain default --password {{ADMIN_PASS}} admin'
- name: 创建 admin 角色
  shell: bash -login -c 'export OS_TOKEN=7027356a188bc8247884;export OS_URL=http://{{CONTROLLER_VIP}}:35357/v3;export OS_IDENTITY_API_VERSION=3;openstack role create admin'
- name: 添加``admin`` 角色到 admin 项目和用户上
  shell: bash -login -c 'export OS_TOKEN=7027356a188bc8247884;export OS_URL=http://{{CONTROLLER_VIP}}:35357/v3;export OS_IDENTITY_API_VERSION=3;openstack role add --project admin --user admin admin'
- name: 创建每个服务包含独有用户的service 项目
  shell: bash -login -c 'export OS_TOKEN=7027356a188bc8247884;export OS_URL=http://{{CONTROLLER_VIP}}:35357/v3;export OS_IDENTITY_API_VERSION=3;openstack project create --domain default --description "Service Project" service'
- name: 创建 user 角色
  shell: bash -login -c 'export OS_TOKEN=7027356a188bc8247884;export OS_URL=http://{{CONTROLLER_VIP}}:35357/v3;export OS_IDENTITY_API_VERSION=3;openstack role create user'
- name: 配置admin-openrc.sh
  shell: \cp {{MAJOR_CONF_PATH}}/keystone/admin-openrc.sh /home/;
         sed -i "s/ADMIN_PASS/{{ADMIN_PASS}}/g" /home/admin-openrc.sh;
         sed -i "s/CONTROLLER_VIP/{{CONTROLLER_VIP}}/g" /home/admin-openrc.sh;
         source /home/admin-openrc.sh

