---

- name: 配置neutron.conf
  shell: crudini --set /etc/neutron/neutron.conf DEFAULT transport_url "rabbit://openstack:{{RABBIT_PASS}}@{{MAJOR_IP}},openstack:{{RABBIT_PASS}}@{{STANDBY_IP}}";
         crudini --set /etc/neutron/neutron.conf DEFAULT auth_strategy keystone;
         crudini --set /etc/neutron/neutron.conf keystone_authtoken auth_uri "http://{{CONTROLLER_VIP}}:5000";
         crudini --set /etc/neutron/neutron.conf keystone_authtoken auth_url "http://{{CONTROLLER_VIP}}:35357";
         crudini --set /etc/neutron/neutron.conf keystone_authtoken memcached_servers "{{MAJOR_IP}}:11211,{{STANDBY_IP}}:11211";
         crudini --set /etc/neutron/neutron.conf keystone_authtoken auth_type password;
         crudini --set /etc/neutron/neutron.conf keystone_authtoken project_domain_name default;
         crudini --set /etc/neutron/neutron.conf keystone_authtoken user_domain_name default;
         crudini --set /etc/neutron/neutron.conf keystone_authtoken project_name service;
         crudini --set /etc/neutron/neutron.conf keystone_authtoken username neutron;
         crudini --set /etc/neutron/neutron.conf keystone_authtoken password {{NEUTRON_PASS}};
         crudini --set /etc/neutron/neutron.conf oslo_concurrency lock_path /var/lib/neutron/tmp

- name: 配置linuxbridge_agent.ini
  shell: crudini --set /etc/neutron/plugins/ml2/linuxbridge_agent.ini linux_bridge physical_interface_mappings "provider:eth2";
         crudini --set /etc/neutron/plugins/ml2/linuxbridge_agent.ini vxlan enable_vxlan true;
         COMPUTE_IP=`crudini --get /root/ip.txt ip eth1`;
         crudini --set /etc/neutron/plugins/ml2/linuxbridge_agent.ini vxlan local_ip $COMPUTE_IP;
         crudini --set /etc/neutron/plugins/ml2/linuxbridge_agent.ini vxlan l2_population true;
         crudini --set /etc/neutron/plugins/ml2/linuxbridge_agent.ini securitygroup enable_security_group true;
         crudini --set /etc/neutron/plugins/ml2/linuxbridge_agent.ini securitygroup firewall_driver "neutron.agent.linux.iptables_firewall.IptablesFirewallDriver"

- name: 配置nova.conf
  shell: crudini --set /etc/nova/nova.conf neutron url "http://{{CONTROLLER_VIP}}:9696";
         crudini --set /etc/nova/nova.conf neutron auth_url "http://{{CONTROLLER_VIP}}:35357";
         crudini --set /etc/nova/nova.conf neutron auth_type password;
         crudini --set /etc/nova/nova.conf neutron project_domain_name default;
         crudini --set /etc/nova/nova.conf neutron user_domain_name default;
         crudini --set /etc/nova/nova.conf neutron region_name RegionOne;
         crudini --set /etc/nova/nova.conf neutron project_name service;
         crudini --set /etc/nova/nova.conf neutron username neutron;
         crudini --set /etc/nova/nova.conf neutron password {{NEUTRON_PASS}}

- name: 启动neutron相关服务
  shell: systemctl restart openstack-nova-compute.service;
         systemctl enable neutron-linuxbridge-agent.service;
         systemctl start neutron-linuxbridge-agent.service
