---

- name: 导入nova数据库
  shell: mysql -uroot -p{{DB_PASS}}< {{MAJOR_CONF_PATH}}/nova/nova.sql
- name: 创建 nova 用户;创建服务；创建三种接口类型
  shell: bash -login -c 'source /home/admin-openrc.sh;openstack user create --domain default --password NOVA_PASS nova;
         openstack role add --project service --user nova admin;
         openstack service create --name nova --description "OpenStack Compute" compute;
         openstack endpoint create --region RegionOne compute public http://{{CONTROLLER_VIP}}:8774/v2.1/%\(tenant_id\)s;
         openstack endpoint create --region RegionOne compute internal http://{{CONTROLLER_VIP}}:8774/v2.1/%\(tenant_id\)s;
         openstack endpoint create --region RegionOne compute admin http://{{CONTROLLER_VIP}}:8774/v2.1/%\(tenant_id\)s'
- name: 配置nova.conf
  shell: crudini --set /etc/nova/nova.conf DEFAULT enabled_apis '"osapi_compute,metadata"';
         crudini --set /etc/nova/nova.conf api_database connection '"mysql+pymysql://nova:NOVA_DBPASS@{{MAJOR_IP}}/nova_api"';
         crudini --set /etc/nova/nova.conf api_database slave_connection '"mysql+pymysql://nova:NOVA_DBPASS@{{STANDBY_IP}}/nova_api"';
         crudini --set /etc/nova/nova.conf database connection '"mysql+pymysql://nova:NOVA_DBPASS@{{MAJOR_IP}}/nova"';
         crudini --set /etc/nova/nova.conf database slave_connection '"mysql+pymysql://nova:NOVA_DBPASS@{{STANDBY_IP}}/nova"';
         crudini --set /etc/nova/nova.conf DEFAULT transport_url rabbit://openstack:RABBIT_PASS@{{MAJOR_IP}}:5672,openstack:RABBIT_PASS@{{STANDBY_IP}}:5672;
         crudini --set /etc/nova/nova.conf DEFAULT auth_strategy keystone;
         crudini --set /etc/nova/nova.conf keystone_authtoken auth_uri '"http://{{CONTROLLER_VIP}}:5000"';
         crudini --set /etc/nova/nova.conf keystone_authtoken auth_url '"http://{{CONTROLLER_VIP}}:35357"';
         crudini --set /etc/nova/nova.conf keystone_authtoken memcached_servers '"{{MAJOR_IP}}:11211,{{STANDBY_IP}}:11211"';
         crudini --set /etc/nova/nova.conf keystone_authtoken auth_type password;
         crudini --set /etc/nova/nova.conf keystone_authtoken project_domain_name default;
         crudini --set /etc/nova/nova.conf keystone_authtoken user_domain_name default;
         crudini --set /etc/nova/nova.conf keystone_authtoken project_name service;
         crudini --set /etc/nova/nova.conf keystone_authtoken username nova;
         crudini --set /etc/nova/nova.conf keystone_authtoken password NOVA_PASS;
         crudini --set /etc/nova/nova.conf DEFAULT my_ip {{MAJOR_IP}};
         crudini --set /etc/nova/nova.conf DEFAULT use_neutron True;
         crudini --set /etc/nova/nova.conf DEFAULT firewall_driver nova.virt.firewall.NoopFirewallDriver;
         crudini --set /etc/nova/nova.conf DEFAULT vnc_enabled false;
         crudini --set /etc/nova/nova.conf DEFAULT web /usr/share/spice-html5;
         crudini --set /etc/nova/nova.conf spice html5proxy_host {{MAJOR_IP}};
         crudini --set /etc/nova/nova.conf spice html5proxy_port 6082;
         crudini --set /etc/nova/nova.conf spice html5proxy_base_url '"http://{{MAJOR_IP}}:6082/spice_auto.html"';
         crudini --set /etc/nova/nova.conf spice enabled true;
         crudini --set /etc/nova/nova.conf spice agent_enabled true;
         crudini --set /etc/nova/nova.conf spice keymap en-us;
         crudini --set /etc/nova/nova.conf glance api_servers http://{{CONTROLLER_VIP}}:9292;
         crudini --set /etc/nova/nova.conf oslo_concurrency lock_path /var/lib/nova/tmp;
         crudini --set /etc/nova/nova.conf DEFAULT osapi_compute_listen {{MAJOR_IP}};
         crudini --set /etc/nova/nova.conf DEFAULT metadata_listen {{MAJOR_IP}}
- name: 同步数据库
  shell: su -s /bin/sh -c "nova-manage api_db sync" nova;su -s /bin/sh -c "nova-manage db sync" nova
- name: 启动openstack-nova-api服务，并设置为开机启动
  service: name=openstack-nova-api state=started enabled=true
- name: 启动openstack-nova-scheduler服务，并设置为开机启动
  service: name=openstack-nova-scheduler state=started enabled=true
- name: 启动openstack-nova-conductor服务，并设置开机启动
  service: name=openstack-nova-conductor state=started enabled=true
- name: 启动openstack-nova-spicehtml5proxy服务，并设置开机启动
  service: name=openstack-nova-spicehtml5proxy state=started enabled=true
- name: 添加nova-consoleauth守护进程到pcs
  shell: pcs resource create nova-consoleauth systemd:openstack-nova-consoleauth --clone
- name: 设置pcs启动顺序
  shell: pcs constraint order start vip then nova-consoleauth-clone kind=Optional
- name: 配置资源捆绑关系
  shell: pcs constraint colocation add nova-consoleauth-clone with vip

