---

- name: 安装nova相关服务
  shell: yum -y install openstack-nova-api openstack-nova-conductor openstack-nova-console openstack-nova-novncproxy openstack-nova-scheduler openstack-nova-placement-api
- name: 配置nova.conf
  shell: crudini --set /etc/nova/nova.conf DEFAULT enabled_apis "osapi_compute,metadata";
         crudini --set /etc/nova/nova.conf DEFAULT transport_url "rabbit://openstack:{{RABBIT_PASS}}@{{MAJOR_IP}},openstack:{{RABBIT_PASS}}@{{STANDBY_IP}}";
         crudini --set /etc/nova/nova.conf DEFAULT my_ip {{STANDBY_IP}};
         crudini --set /etc/nova/nova.conf DEFAULT use_neutron True;
         crudini --set /etc/nova/nova.conf DEFAULT firewall_driver "nova.virt.firewall.NoopFirewallDriver";
         crudini --set /etc/nova/nova.conf api_database connection "mysql+pymysql://nova:{{NOVA_DBPASS}}@{{MAJOR_IP}}/nova_api";
         crudini --set /etc/nova/nova.conf api_database slave_connection "mysql+pymysql://nova:{{NOVA_DBPASS}}@{{STANDBY_IP}}/nova_api";
         crudini --set /etc/nova/nova.conf database connection "mysql+pymysql://nova:{{NOVA_DBPASS}}@{{MAJOR_IP}}/nova";
         crudini --set /etc/nova/nova.conf database slave_connection "mysql+pymysql://nova:{{NOVA_DBPASS}}@{{STANDBY_IP}}/nova";
         crudini --set /etc/nova/nova.conf api auth_strategy keystone;
         crudini --set /etc/nova/nova.conf keystone_authtoken auth_uri "http://{{CONTROLLER_VIP}}:5000";
         crudini --set /etc/nova/nova.conf keystone_authtoken auth_url "http://{{CONTROLLER_VIP}}:35357";
         crudini --set /etc/nova/nova.conf keystone_authtoken memcached_servers "{{MAJOR_IP}}:11211,{{STANDBY_IP}}:11211";
         crudini --set /etc/nova/nova.conf keystone_authtoken auth_type password;
         crudini --set /etc/nova/nova.conf keystone_authtoken project_domain_name default;
         crudini --set /etc/nova/nova.conf keystone_authtoken user_domain_name default;
         crudini --set /etc/nova/nova.conf keystone_authtoken project_name service;
         crudini --set /etc/nova/nova.conf keystone_authtoken username nova;
         crudini --set /etc/nova/nova.conf keystone_authtoken password {{NOVA_DBPASS}};
         crudini --set /etc/nova/nova.conf vnc enabled "true";
         crudini --set /etc/nova/nova.conf vnc vncserver_listen \my_ip;
         crudini --set /etc/nova/nova.conf vnc vncserver_proxyclient_address \my_ip;
         crudini --set /etc/nova/nova.conf glance api_servers "http://{{CONTROLLER_VIP}}:9292";
         crudini --set /etc/nova/nova.conf oslo_concurrency lock_path "/var/lib/nova/tmp";
         crudini --set /etc/nova/nova.conf placement os_region_name RegionOne;
         crudini --set /etc/nova/nova.conf placement project_domain_name Default;
         crudini --set /etc/nova/nova.conf placement project_name service;
         crudini --set /etc/nova/nova.conf placement auth_type password;
         crudini --set /etc/nova/nova.conf placement user_domain_name Default;
         crudini --set /etc/nova/nova.conf placement auth_url "http://{{CONTROLLER_VIP}}:35357/v3";
         crudini --set /etc/nova/nova.conf placement username placement;
         crudini --set /etc/nova/nova.conf placement password "{{PLACEMENT_PASS}}";
         crudini --set /etc/nova/nova.conf DEFAULT osapi_compute_listen {{STANDBY_IP}};
         crudini --set /etc/nova/nova.conf DEFAULT metadata_listen {{STANDBY_IP}}

- name: 修改http配置
  shell: sed -i '/<\/VirtualHost>/i\  <Directory />' /etc/httpd/conf.d/00-nova-placement-api.conf;
         sed -i '/<\/VirtualHost>/i\    Options All' /etc/httpd/conf.d/00-nova-placement-api.conf;
         sed -i '/<\/VirtualHost>/i\    AllowOverride All' /etc/httpd/conf.d/00-nova-placement-api.conf;
         sed -i '/<\/VirtualHost>/i\    Require all granted' /etc/httpd/conf.d/00-nova-placement-api.conf;
         sed -i '/<\/VirtualHost>/i\  </Directory>' /etc/httpd/conf.d/00-nova-placement-api.conf;
         sed -i '/<\/VirtualHost>/i\  <Directory /usr/bin/nova-placement-api>' /etc/httpd/conf.d/00-nova-placement-api.conf;
         sed -i '/<\/VirtualHost>/i\    Options All' /etc/httpd/conf.d/00-nova-placement-api.conf;
         sed -i '/<\/VirtualHost>/i\    AllowOverride All' /etc/httpd/conf.d/00-nova-placement-api.conf;
         sed -i '/<\/VirtualHost>/i\    Require all granted' /etc/httpd/conf.d/00-nova-placement-api.conf;
         sed -i '/<\/VirtualHost>/i\  </Directory>' /etc/httpd/conf.d/00-nova-placement-api.conf;
         sed -i "s/^Listen 8778/Listen {{STANDBY_IP}}:8778/" /etc/httpd/conf.d/00-nova-placement-api.conf
- name: 启动nova服务
  shell: systemctl restart httpd;
         systemctl enable openstack-nova-api.service openstack-nova-consoleauth.service openstack-nova-scheduler.service openstack-nova-conductor.service openstack-nova-novncproxy.service;
         systemctl start openstack-nova-api.service openstack-nova-consoleauth.service openstack-nova-scheduler.service openstack-nova-conductor.service openstack-nova-novncproxy.service

