---

- name: 创建服务实体与API
  shell: source /home/admin-openrc.sh;
         openstack user create --domain default --password {{GLANCE_PASS}} glance;
         openstack role add --project service --user glance admin;
         openstack service create --name glance --description "OpenStack Image" image;
         openstack endpoint create --region RegionOne image public http://{{MAJOR_IP}}:9292;
         openstack endpoint create --region RegionOne image internal http://{{MAJOR_IP}}:9292;
         openstack endpoint create --region RegionOne image admin http://{{MAJOR_IP}}:9292;
- name: 配置glance-api.conf
  shell: crudini --set /etc/glance/glance-api.conf database connection "mysql+pymysql://glance:{{GLANCE_PASS}}@{{MAJOR_IP}}/glance";
         crudini --set /etc/glance/glance-api.conf keystone_authtoken auth_uri "http://{{MAJOR_IP}}:5000";
         crudini --set /etc/glance/glance-api.conf keystone_authtoken auth_url "http://{{MAJOR_IP}}:35357";
         crudini --set /etc/glance/glance-api.conf keystone_authtoken memcached_servers {{MAJOR_IP}}:11211;
         crudini --set /etc/glance/glance-api.conf keystone_authtoken auth_type password;
         crudini --set /etc/glance/glance-api.conf keystone_authtoken project_domain_name default;
         crudini --set /etc/glance/glance-api.conf keystone_authtoken user_domain_name default;
         crudini --set /etc/glance/glance-api.conf keystone_authtoken project_name service;
         crudini --set /etc/glance/glance-api.conf keystone_authtoken username glance;
         crudini --set /etc/glance/glance-api.conf keystone_authtoken password {{GLANCE_PASS}};
         crudini --set /etc/glance/glance-api.conf paste_deploy flavor keystone;
         crudini --set /etc/glance/glance-api.conf glance_store stores file,http;
         crudini --set /etc/glance/glance-api.conf glance_store default_store file;
         crudini --set /etc/glance/glance-api.conf glance_store filesystem_store_datadir /var/lib/glance/images/
- name: 配置glance-registry.conf
  shell: crudini --set /etc/glance/glance-registry.conf database connection "mysql+pymysql://glance:{{GLANCE_PASS}}@{{MAJOR_IP}}/glance";
         crudini --set /etc/glance/glance-registry.conf keystone_authtoken auth_uri http://{{MAJOR_IP}}:5000;
         crudini --set /etc/glance/glance-registry.conf keystone_authtoken auth_url http://{{MAJOR_IP}}:35357;
         crudini --set /etc/glance/glance-registry.conf keystone_authtoken memcached_servers {{MAJOR_IP}}:11211;
         crudini --set /etc/glance/glance-registry.conf keystone_authtoken auth_type password;
         crudini --set /etc/glance/glance-registry.conf keystone_authtoken project_domain_name default;
         crudini --set /etc/glance/glance-registry.conf keystone_authtoken user_domain_name default;
         crudini --set /etc/glance/glance-registry.conf keystone_authtoken project_name service;
         crudini --set /etc/glance/glance-registry.conf keystone_authtoken username glance;
         crudini --set /etc/glance/glance-registry.conf keystone_authtoken password {{GLANCE_PASS}};
         crudini --set /etc/glance/glance-registry.conf paste_deploy flavor keystone
- name: 同步数据库
  shell: su -s /bin/sh -c "glance-manage db_sync" glance
- name: 启动glance服务
  shell: systemctl enable openstack-glance-api.service openstack-glance-registry.service;
         systemctl start openstack-glance-api.service openstack-glance-registry.service

