---

- name: 导入cinder数据库
  shell: mysql -uroot -p{{DB_PASS}}< {{MAJOR_CONF_PATH}}/cinder/cinder.sql
- name: 创建 cinder 用户,创建服务,创建三种接口类型
  shell: bash -login -c 'source /home/admin-openrc.sh;
         openstack user create --domain default --password CINDER_PASS cinder;
         openstack role add --project service --user cinder admin;
         openstack service create --name cinder --description "OpenStack Block Storage" volume;
         openstack service create --name cinderv2 --description "OpenStack Block Storage" volumev2;
         openstack endpoint create --region RegionOne volume public http://{{CONTROLLER_VIP}}:8776/v1/%\(tenant_id\)s;
         openstack endpoint create --region RegionOne volume internal http://{{CONTROLLER_VIP}}:8776/v1/%\(tenant_id\)s;
         openstack endpoint create --region RegionOne volume admin http://{{CONTROLLER_VIP}}:8776/v1/%\(tenant_id\)s;
         openstack endpoint create --region RegionOne volumev2 public http://{{CONTROLLER_VIP}}:8776/v2/%\(tenant_id\)s;
         openstack endpoint create --region RegionOne volumev2 internal http://{{CONTROLLER_VIP}}:8776/v2/%\(tenant_id\)s;
         openstack endpoint create --region RegionOne volumev2 admin http://{{CONTROLLER_VIP}}:8776/v2/%\(tenant_id\)s'
- name: 配置cinder.conf
  shell: crudini --set /etc/cinder/cinder.conf database connection "mysql+pymysql://cinder:CINDER_DBPASS@{{MAJOR_IP}}/cinder";
         crudini --set /etc/cinder/cinder.conf database slave_connection "mysql+pymysql://cinder:CINDER_DBPASS@{{STANDBY_IP}}/cinder";
         crudini --set /etc/cinder/cinder.conf DEFAULT transport_url rabbit://openstack:RABBIT_PASS@{{MAJOR_IP}}:5672,openstack:RABBIT_PASS@{{STANDBY_IP}}:5672
         crudini --set /etc/cinder/cinder.conf DEFAULT auth_strategy keystone;
         crudini --set /etc/cinder/cinder.conf keystone_authtoken auth_uri "http://{{CONTROLLER_VIP}}:5000";
         crudini --set /etc/cinder/cinder.conf keystone_authtoken auth_url "http://{{CONTROLLER_VIP}}:35357";
         crudini --set /etc/cinder/cinder.conf keystone_authtoken memcached_servers "{{MAJOR_IP}}:11211,{{STANDBY_IP}}:11211";
         crudini --set /etc/cinder/cinder.conf keystone_authtoken auth_type password;
         crudini --set /etc/cinder/cinder.conf keystone_authtoken project_domain_name default;
         crudini --set /etc/cinder/cinder.conf keystone_authtoken user_domain_name default;
         crudini --set /etc/cinder/cinder.conf keystone_authtoken project_name service;
         crudini --set /etc/cinder/cinder.conf keystone_authtoken username cinder;
         crudini --set /etc/cinder/cinder.conf keystone_authtoken password CINDER_PASS;
         crudini --set /etc/cinder/cinder.conf DEFAULT my_ip {{MAJOR_IP}};
         crudini --set /etc/cinder/cinder.conf oslo_concurrency lock_path /var/lib/cinder/tmp;
         crudini --set /etc/cinder/cinder.conf DEFAULT osapi_volume_listen {{MAJOR_IP}};
         crudini --set /etc/cinder/cinder.conf DEFAULT glance_api_servers "http://{{CONTROLLER_VIP}}:9292"
- name: 配置存储柜相关配置
  shell: crudini --set /etc/cinder/cinder.conf DEFAULT use_multipath_for_image_xfer True;
         crudini --set /etc/cinder/cinder.conf DEFAULT enforce_multipath_for_image_xfer True;
         crudini --set /etc/cinder/cinder.conf DEFAULT volume_driver cinder.volume.drivers.huawei.huawei_driver.HuaweiTISCSIDriver;
         crudini --set /etc/cinder/cinder.conf DEFAULT cinder_huawei_conf_file /etc/cinder/cinder_huawei_conf.xml;
         \cp -r {{MAJOR_CONF_PATH}}/cinder/cinder_huawei_conf.xml /etc/cinder/;
         rm -rf /usr/lib/python2.7/site-packages/cinder/volume/drivers/huawei/;
         \cp -r {{MAJOR_CODE_PATH}}/cinder/huawei /usr/lib/python2.7/site-packages/cinder/volume/drivers/;
         rm -f /usr/lib/python2.7/site-packages/os_brick/initiator/connector.py;
         \cp -r {{MAJOR_CONF_PATH}}/cinder/connector.py /usr/lib/python2.7/site-packages/os_brick/initiator/
- name: 同步cinder数据库
  shell: su -s /bin/sh -c "cinder-manage db sync" cinder
- name: 启动cinder服务
  shell: crudini --set /etc/nova/nova.conf cinder os_region_name RegionOne;
         systemctl restart openstack-nova-api.service;
         systemctl enable openstack-cinder-api.service openstack-cinder-scheduler.service openstack-cinder-volume.service;
         systemctl start openstack-cinder-api.service openstack-cinder-scheduler.service openstack-cinder-volume.service
