---

- hosts: pike
  vars_files:
  - /root/pike/group_vars/all
  tasks:
  - name: 检查网络是否畅通
    shell: ping -c 3 time1.aliyun.com
  - name: 同步时间
    shell: ntpdate time1.aliyun.com;
           hwclock -w

- hosts: pike_controller
  vars_files:
  - /root/pike/group_vars/all
  tasks:
  - name: 复制chronyd配置文件
    copy: src="{{pike_conf}}/chrony.conf" dest="/etc/chrony.conf"

- hosts: pike_compute
  vars_files:
  - /root/pike/group_vars/all
  tasks:
  - name: 复制chronyd配置文件
    copy: src="{{pike_conf}}/chrony.conf" dest="/etc/chrony.conf"
  - name: 同步时间
    shell: echo "server controller iburst" >> /etc/chrony.conf

- hosts: pike
  tasks:
  - name: 开启chronyd服务，并设为开机启动
    shell: systemctl enable chronyd.service;
           systemctl start chronyd.service;
           systemctl restart chronyd.service
