---

- hosts: pike_controller
  tasks:
  - name:
    shell: source /home/admin-openrc.sh;
           openstack compute service list --service nova-compute;
           su -s /bin/sh -c "nova-manage cell_v2 discover_hosts --verbose" nova

