---

- hosts: pike_controller
  tasks:
  - name: 控制节点需要安装的包
    shell: yum -y install chrony crudini;
           yum -y install centos-release-openstack-pike;
           yum -y install https://rdoproject.org/repos/rdo-release.rpm;
           yum -y upgrade;
           yum -y install python-openstackclient;
           yum -y install openstack-selinux;
           yum -y install mariadb mariadb-server python2-PyMySQL expect;
           yum -y install rabbitmq-server;
           yum -y install memcached python-memcached;
           yum -y install openstack-keystone httpd mod_wsgi;
           yum -y install openstack-glance;
           yum -y install openstack-nova-api openstack-nova-conductor openstack-nova-console openstack-nova-novncproxy openstack-nova-scheduler openstack-nova-placement-api;
           yum -y install openstack-neutron openstack-neutron-ml2 openstack-neutron-linuxbridge ebtables;
           yum -y install openstack-dashboard

- hosts: pike_compute
  tasks:
  - name: 计算节点需要安装的包
    shell: yum -y install chrony crudini;
           yum -y install centos-release-openstack-pike;
           yum -y install https://rdoproject.org/repos/rdo-release.rpm;
           yum -y upgrade;
           yum -y install python-openstackclient;
           yum -y install openstack-selinux;
           yum -y install openstack-nova-compute;
           yum -y install openstack-neutron-linuxbridge ebtables ipset
