---

- name: 配置neutron.conf
  shell: crudini --set /etc/neutron/neutron.conf DEFAULT transport_url rabbit://openstack:RABBIT_PASS@{{MAJOR_IP}}:5672,openstack:RABBIT_PASS@{{STANDBY_IP}}:5672;
         crudini --set /etc/neutron/neutron.conf DEFAULT auth_strategy keystone;
         crudini --set /etc/neutron/neutron.conf keystone_authtoken auth_uri "http://{{CONTROLLER_VIP}}:5000";
         crudini --set /etc/neutron/neutron.conf keystone_authtoken auth_url "http://{{CONTROLLER_VIP}}:35357";
         crudini --set /etc/neutron/neutron.conf keystone_authtoken memcached_servers "{{MAJOR_IP}}:11211,{{STANDBY_IP}}:11211";
         crudini --set /etc/neutron/neutron.conf keystone_authtoken auth_type password;
         crudini --set /etc/neutron/neutron.conf keystone_authtoken project_domain_name Default;
         crudini --set /etc/neutron/neutron.conf keystone_authtoken user_domain_name Default;
         crudini --set /etc/neutron/neutron.conf keystone_authtoken project_name service;
         crudini --set /etc/neutron/neutron.conf keystone_authtoken username neutron;
         crudini --set /etc/neutron/neutron.conf keystone_authtoken password NEUTRON_PASS;
         crudini --set /etc/neutron/neutron.conf oslo_concurrency lock_path /var/lib/neutron/tmp

- name: 配置openvswitch_agent.ini
  shell: crudini --set /etc/neutron/plugins/ml2/openvswitch_agent.ini ovs local_ip {{COMPUTE_TUNNEL_IP}};
         crudini --set /etc/neutron/plugins/ml2/openvswitch_agent.ini ovs bridge_mappings "external:br-ex";
         crudini --set /etc/neutron/plugins/ml2/openvswitch_agent.ini agent tunnel_types vxlan;
         crudini --set /etc/neutron/plugins/ml2/openvswitch_agent.ini agent l2_population True;
         crudini --set /etc/neutron/plugins/ml2/openvswitch_agent.ini agent prevent_arp_spoofing True;
         crudini --set /etc/neutron/plugins/ml2/openvswitch_agent.ini securitygroup firewall_driver neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver;
         crudini --set /etc/neutron/plugins/ml2/openvswitch_agent.ini securitygroup enable_security_group True

- name: 追加配置nova.conf
  shell: crudini --set /etc/nova/nova.conf neutron url "http://{{CONTROLLER_VIP}}:9696";
         crudini --set /etc/nova/nova.conf neutron auth_url "http://{{CONTROLLER_VIP}}:35357";
         crudini --set /etc/nova/nova.conf neutron auth_type password;
         crudini --set /etc/nova/nova.conf neutron project_domain_name Default;
         crudini --set /etc/nova/nova.conf neutron user_domain_name Default;
         crudini --set /etc/nova/nova.conf neutron region_name RegionOne;
         crudini --set /etc/nova/nova.conf neutron project_name service;
         crudini --set /etc/nova/nova.conf neutron username neutron;
         crudini --set /etc/nova/nova.conf neutron password NEUTRON_PASS

- name: 开启服务
  shell: systemctl enable openvswitch.service;
         systemctl start openvswitch.service;
         ovs-vsctl add-br br-ex;
         systemctl restart openstack-nova-compute.service;
         systemctl enable neutron-openvswitch-agent.service;
         systemctl start neutron-openvswitch-agent.service
