---

- name: 安装包，配置/etc/nova/nova.conf
  shell: COMPUTE_IP=`crudini --get /root/ip.txt ip eth0`;
         crudini --set /etc/nova/nova.conf DEFAULT enabled_apis "osapi_compute,metadata";
         crudini --set /etc/nova/nova.conf DEFAULT transport_url "rabbit://openstack:{{RABBIT_PASS}}@{{MAJOR_IP}},openstack:{{RABBIT_PASS}}@{{STANDBY_IP}}";
         crudini --set /etc/nova/nova.conf DEFAULT vnc_enabled false;
         crudini --set /etc/nova/nova.conf DEFAULT web /usr/share/spice-html5;
         crudini --set /etc/nova/nova.conf DEFAULT resume_guests_state_on_host_boot true;
         crudini --set /etc/nova/nova.conf DEFAULT ram_allocation_ratio 1.2;
         crudini --set /etc/nova/nova.conf api auth_strategy keystone;
         crudini --set /etc/nova/nova.conf keystone_authtoken auth_uri "http://{{CONTROLLER_VIP}}:5000";
         crudini --set /etc/nova/nova.conf keystone_authtoken auth_url "http://{{CONTROLLER_VIP}}:35357";
         crudini --set /etc/nova/nova.conf keystone_authtoken memcached_servers "{{MAJOR_IP}}:11211,{{STANDBY_IP}}:11211"; 
         crudini --set /etc/nova/nova.conf keystone_authtoken auth_type password;
         crudini --set /etc/nova/nova.conf keystone_authtoken project_domain_name default;
         crudini --set /etc/nova/nova.conf keystone_authtoken user_domain_name default;
         crudini --set /etc/nova/nova.conf keystone_authtoken project_name service;
         crudini --set /etc/nova/nova.conf keystone_authtoken username nova;
         crudini --set /etc/nova/nova.conf keystone_authtoken password {{NOVA_DBPASS}};
         crudini --set /etc/nova/nova.conf DEFAULT my_ip $COMPUTE_IP;
         crudini --set /etc/nova/nova.conf DEFAULT use_neutron True;
         crudini --set /etc/nova/nova.conf DEFAULT firewall_driver  "nova.virt.firewall.NoopFirewallDriver";
         crudini --set /etc/nova/nova.conf spice html5proxy_base_url "http://{{CONTROLLER_VIP}}:6082/spice_auto.html";
         crudini --set /etc/nova/nova.conf spice server_listen 0.0.0.0;
         crudini --set /etc/nova/nova.conf spice server_proxyclient_address $COMPUTE_IP;
         crudini --set /etc/nova/nova.conf spice enabled true;
         crudini --set /etc/nova/nova.conf spice agent_enabled False;
         crudini --set /etc/nova/nova.conf spice keymap en-us;
         crudini --set /etc/nova/nova.conf glance api_servers "http://{{CONTROLLER_VIP}}:9292";
         crudini --set /etc/nova/nova.conf oslo_concurrency lock_path "/var/lib/nova/tmp";
         crudini --set /etc/nova/nova.conf placement os_region_name RegionOne;
         crudini --set /etc/nova/nova.conf placement project_domain_name Default;
         crudini --set /etc/nova/nova.conf placement project_name service;
         crudini --set /etc/nova/nova.conf placement auth_type password;
         crudini --set /etc/nova/nova.conf placement user_domain_name Default;
         crudini --set /etc/nova/nova.conf placement auth_url "http://{{CONTROLLER_VIP}}:35357/v3";
         crudini --set /etc/nova/nova.conf placement username placement;
         crudini --set /etc/nova/nova.conf placement password {{PLACEMENT_PASS}}
         crudini --set /etc/nova/nova.conf libvirt virt_type kvm;
         crudini --set /etc/nova/nova.conf libvirt use_usb_tablet true
- name: 启动nova服务
  shell: systemctl enable libvirtd.service openstack-nova-compute.service;
         systemctl start libvirtd.service openstack-nova-compute.service
