---

- name: 配置nova.conf
  shell: CONTROLLER_IP=`ifconfig eth0 | grep -w inet | awk '{print $2}'`;
         crudini --set /etc/nova/nova.conf DEFAULT enabled_apis osapi_compute,metadata;
         crudini --set /etc/nova/nova.conf DEFAULT transport_url rabbit://openstack:RABBIT_PASS@{{MAJOR_IP}}:5672,openstack:RABBIT_PASS@{{STANDBY_IP}}:5672;
         crudini --set /etc/nova/nova.conf DEFAULT auth_strategy keystone;
         crudini --set /etc/nova/nova.conf keystone_authtoken auth_uri "http://{{CONTROLLER_VIP}}:5000";
         crudini --set /etc/nova/nova.conf keystone_authtoken auth_url "http://{{CONTROLLER_VIP}}:35357";
         crudini --set /etc/nova/nova.conf keystone_authtoken memcached_servers "{{MAJOR_IP}}:11211,{{STANDBY_IP}}:11211";
         crudini --set /etc/nova/nova.conf keystone_authtoken auth_type password;
         crudini --set /etc/nova/nova.conf keystone_authtoken project_domain_name Default;
         crudini --set /etc/nova/nova.conf keystone_authtoken user_domain_name Default;
         crudini --set /etc/nova/nova.conf keystone_authtoken project_name service;
         crudini --set /etc/nova/nova.conf keystone_authtoken username nova;
         crudini --set /etc/nova/nova.conf keystone_authtoken password NOVA_PASS;
         crudini --set /etc/nova/nova.conf DEFAULT my_ip $CONTROLLER_IP;
         crudini --set /etc/nova/nova.conf DEFAULT use_neutron True;
         crudini --set /etc/nova/nova.conf DEFAULT firewall_driver nova.virt.firewall.NoopFirewallDriver;
         crudini --set /etc/nova/nova.conf DEFAULT vnc_enabled false;
         crudini --set /etc/nova/nova.conf DEFAULT web /usr/share/spice-html5;
         crudini --set /etc/nova/nova.conf spice html5proxy_base_url "http://{{CONTROLLER_VIP}}:6082/spice_auto.html";
         crudini --set /etc/nova/nova.conf spice server_listen 0.0.0.0;
         crudini --set /etc/nova/nova.conf spice server_proxyclient_address $CONTROLLER_IP;
         crudini --set /etc/nova/nova.conf spice enabled true;
         crudini --set /etc/nova/nova.conf spice agent_enabled False;
         crudini --set /etc/nova/nova.conf spice keymap en-us;
         crudini --set /etc/nova/nova.conf glance api_servers http://{{CONTROLLER_VIP}}:9292;
         crudini --set /etc/nova/nova.conf oslo_concurrency lock_path /var/lib/nova/tmp;
         crudini --set /etc/nova/nova.conf libvirt virt_type kvm;
         crudini --set /etc/nova/nova.conf libvirt use_usb_tablet true;
         crudini --set /etc/nova/nova.conf DEFAULT resume_guests_state_on_host_boot true;
         crudini --set /etc/nova/nova.conf DEFAULT ram_allocation_ratio 1.2
- name: nova配置互信
  shell: usermod -s /bin/bash nova;
         mkdir /var/lib/nova/.ssh;
         chmod 700 /var/lib/nova/.ssh;
         cp /root/.ssh/* /var/lib/nova/.ssh/;
         chmod 600 /var/lib/nova/.ssh/config;
         chmod 600 /var/lib/nova/.ssh/id_rsa;
         chmod 600 /var/lib/nova/.ssh/authorized_keys;
         chown -R nova:nova /var/lib/nova/.ssh
- name: 启动libvirtd openstack-nova-comput服务
  shell: systemctl enable libvirtd.service openstack-nova-compute.service;
         systemctl start libvirtd.service openstack-nova-compute.service
