---

- name: 创建服务实体和API
  shell: source /home/admin-openrc.sh;
         openstack user create --domain default --password {{NOVA_PASS}} nova;
         openstack role add --project service --user nova admin;
         openstack service create --name nova --description "OpenStack Compute" compute;
         openstack endpoint create --region RegionOne compute public http://{{MAJOR_IP}}:8774/v2.1;
         openstack endpoint create --region RegionOne compute internal http://{{MAJOR_IP}}:8774/v2.1;
         openstack endpoint create --region RegionOne compute admin http://{{MAJOR_IP}}:8774/v2.1;
         openstack user create --domain default --password {{NOVA_PASS}} placement;
         openstack role add --project service --user placement admin;
         openstack service create --name placement --description "Placement API" placement;
         openstack endpoint create --region RegionOne placement public http://{{MAJOR_IP}}:8778;
         openstack endpoint create --region RegionOne placement internal http://{{MAJOR_IP}}:8778;
         openstack endpoint create --region RegionOne placement admin http://{{MAJOR_IP}}:8778

- name: 配置nova.conf
  shell: crudini --set /etc/nova/nova.conf DEFAULT enabled_apis osapi_compute,metadata;
         crudini --set /etc/nova/nova.conf DEFAULT transport_url rabbit://openstack:{{RABBIT_PASS}}@{{MAJOR_IP}};
         crudini --set /etc/nova/nova.conf DEFAULT my_ip {{MAJOR_IP}};
         crudini --set /etc/nova/nova.conf DEFAULT use_neutron True;
         crudini --set /etc/nova/nova.conf DEFAULT firewall_driver nova.virt.firewall.NoopFirewallDriver;
         crudini --set /etc/nova/nova.conf api_database connection mysql+pymysql://nova:{{NOVA_PASS}}@{{MAJOR_IP}}/nova_api;
         crudini --set /etc/nova/nova.conf database connection mysql+pymysql://nova:{{NOVA_PASS}}@{{MAJOR_IP}}/nova;
         crudini --set /etc/nova/nova.conf api auth_strategy keystone;
         crudini --set /etc/nova/nova.conf keystone_authtoken auth_uri http://{{MAJOR_IP}}:5000;
         crudini --set /etc/nova/nova.conf keystone_authtoken auth_url http://{{MAJOR_IP}}:35357;
         crudini --set /etc/nova/nova.conf keystone_authtoken memcached_servers {{MAJOR_IP}}:11211;
         crudini --set /etc/nova/nova.conf keystone_authtoken auth_type password;
         crudini --set /etc/nova/nova.conf keystone_authtoken project_domain_name default;
         crudini --set /etc/nova/nova.conf keystone_authtoken user_domain_name default;
         crudini --set /etc/nova/nova.conf keystone_authtoken project_name service;
         crudini --set /etc/nova/nova.conf keystone_authtoken username nova;
         crudini --set /etc/nova/nova.conf keystone_authtoken password {{NOVA_PASS}};
         crudini --set /etc/nova/nova.conf vnc enabled true;
         crudini --set /etc/nova/nova.conf vnc vncserver_listen \$my_ip;
         crudini --set /etc/nova/nova.conf vnc vncserver_proxyclient_address \$my_ip;
         crudini --set /etc/nova/nova.conf glance api_servers http://{{MAJOR_IP}}:9292;
         crudini --set /etc/nova/nova.conf oslo_concurrency lock_path /var/lib/nova/tmp;
         crudini --set /etc/nova/nova.conf placement os_region_name RegionOne;
         crudini --set /etc/nova/nova.conf placement project_domain_name Default;
         crudini --set /etc/nova/nova.conf placement project_name service;
         crudini --set /etc/nova/nova.conf placement auth_type password;
         crudini --set /etc/nova/nova.conf placement user_domain_name Default;
         crudini --set /etc/nova/nova.conf placement auth_url http://{{MAJOR_IP}}:35357/v3;
         crudini --set /etc/nova/nova.conf placement username placement;
         crudini --set /etc/nova/nova.conf placement password {{PLACEMENT_PASS}}

- name: 修改http配置
  shell: sed -i '/<\/VirtualHost>/i\  <Directory />' /etc/httpd/conf.d/00-nova-placement-api.conf;
         sed -i '/<\/VirtualHost>/i\    Options All' /etc/httpd/conf.d/00-nova-placement-api.conf;
         sed -i '/<\/VirtualHost>/i\    AllowOverride All' /etc/httpd/conf.d/00-nova-placement-api.conf;
         sed -i '/<\/VirtualHost>/i\    Require all granted' /etc/httpd/conf.d/00-nova-placement-api.conf;
         sed -i '/<\/VirtualHost>/i\  </Directory>' /etc/httpd/conf.d/00-nova-placement-api.conf;
         sed -i '/<\/VirtualHost>/i\  <Directory /usr/bin/nova-placement-api>' /etc/httpd/conf.d/00-nova-placement-api.conf;
         sed -i '/<\/VirtualHost>/i\    Options All' /etc/httpd/conf.d/00-nova-placement-api.conf;
         sed -i '/<\/VirtualHost>/i\    AllowOverride All' /etc/httpd/conf.d/00-nova-placement-api.conf;
         sed -i '/<\/VirtualHost>/i\    Require all granted' /etc/httpd/conf.d/00-nova-placement-api.conf;
         sed -i '/<\/VirtualHost>/i\  </Directory>' /etc/httpd/conf.d/00-nova-placement-api.conf;
         sed -i "s/^Listen 8778/Listen {{MAJOR_IP}}:8778/" /etc/httpd/conf.d/00-nova-placement-api.conf

- name: 重启http服务
  shell: systemctl restart httpd

- name: 同步数据库
  shell: su -s /bin/sh -c "nova-manage api_db sync" nova;
         su -s /bin/sh -c "nova-manage cell_v2 map_cell0" nova;
         su -s /bin/sh -c "nova-manage cell_v2 create_cell --name=cell1 --verbose" nova;
         su -s /bin/sh -c "nova-manage db sync" nova;
         nova-manage cell_v2 list_cells;
         systemctl enable openstack-nova-api.service openstack-nova-consoleauth.service openstack-nova-scheduler.service openstack-nova-conductor.service openstack-nova-novncproxy.service;
         systemctl start openstack-nova-api.service openstack-nova-consoleauth.service openstack-nova-scheduler.service openstack-nova-conductor.service openstack-nova-novncproxy.service

